name: Pipeline GGUF Final

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le code
        uses: actions/checkout@v4

      - name: Installer Python et les outils nécessaires
        run: pip install huggingface_hub gguf torch sentencepiece protobuf

      - name: Cloner llama.cpp
        run: git clone https://github.com/ggerganov/llama.cpp.git

      - name: Lancer la conversion directe
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python3 -c "from huggingface_hub import snapshot_download; snapshot_download(repo_id='ouzaif/Expert-Cyber-Droit-FineTuned', local_dir='model_hf', token='$HF_TOKEN')"
          python3 llama.cpp/convert_hf_to_gguf.py model_hf/ --outfile Expert-Cyber-Droit.gguf --outtype f16
          python3 -c "from huggingface_hub import HfApi; api = HfApi(); api.upload_file(path_or_fileobj='Expert-Cyber-Droit.gguf', path_in_repo='Expert-Cyber-Droit.gguf', repo_id='ouzaif/Expert-Cyber-Droit-GGUF', token='$HF_TOKEN')"
