name: Pipeline MLOps - AutoTrain HF

on:
  push:
    branches:
      - main

jobs:
  orchestrate-ai:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installer les dépendances
        run: pip install huggingface_hub
      - name: Lancer le script d'entraînement
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python train.py
